apiVersion: v1
kind: Namespace
metadata:
  name: abrbird
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-2-portfolio-bot-server-deployment
  namespace: abrbird
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      namespace: abrbird
      labels:
        app: grpc
    spec:
      containers:
        - name: grpc
          image: cr.yandex/crpa8gap9g6vl6hshofn/hw_2_portfolio_bot:__VERSION__
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-2-postgres-deployment
  namespace: abrbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      namespace: abrbird
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
              name: pg
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: "homework_2"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "postgres"
