

application:
  host: app
  grpc_port: 8080
  grpc_gateway_port: 8090
  validateInternal: true

  baseCurrency: "USD"
  historyStartTimeStamp: 1640995200  # 2022-01-01 00:00:00
  historyInterval: 3600  # 1 hour
  availableMarketItems:
    - code: "BTC"
      type: "CryptoCurrency"
    - code: "ETH"
      type: "CryptoCurrency"
    - code: "BNB"
      type: "CryptoCurrency"
    - code: "XRP"
      type: "CryptoCurrency"
    - code: "ADA"
      type: "CryptoCurrency"
    - code: "SOL"
      type: "CryptoCurrency"
    - code: "DOGE"
      type: "CryptoCurrency"

    - code: "AAPL"
      type: "Stock"
    - code: "EQT"
      type: "Stock"
    - code: "UPST"
      type: "Stock"
    - code: "X"
      type: "Stock"
    - code: "EBAY"
      type: "Stock"
    - code: "F"
      type: "Stock"
    - code: "AMZN"
      type: "Stock"

    - code: "AAAU"
      type: "ETF"
    - code: "TQQQ"
      type: "ETF"
    - code: "SPY"
      type: "ETF"
    - code: "UVXY"
      type: "ETF"


clientApiKeys:
  anyClient: "um7L0HzCEFG345wciHj8UYdSjzffA667iFPSxVdFoGWkKLgkv5K3ePQwYyffNPyF"


externalApiKeys:
  telegram: "5370269938:AAF12oGyAVUyyNKqlck3enyXy_zVcOQenXw"


database:
  db: "homework_2"
  host: db
  port: 5432
  user: "postgres"
  password: "postgres"


dataSources:
  - name: "YahooFinance"
    apiKey: "iUg8Cf1tE81FCDIcFSPfC95TSPsKnERw8nbw1iP9"
    url: "https://yfapi.net"
  - name: "AlphaVantage"
    apiKey: "V945IM2AEOYSAW3B"
    url: "https://www.alphavantage.co"